[env]
NODE_ENV = "production"

[tools]
node = ["18.20.8"]
hugo = ["extended_0.155.2"]
"aqua:gohugoio/hugo/hugo-extended" = ["0.155.2"]
"npm:wrangler" = ["4.65.0"]
# "npm:node-vibrant" = ["3.1.4"]
# "npm:photoswipe" = ["4.1.3"]
# "npm:katex" = ["0.15.6"]
#"npm:"
#go = ["1.22.0"]
