[env]
NODE_ENV = "production"

[tools]
node = ["18.20.8"]
hugo = ["extended_0.154.4"]
"aqua:gohugoio/hugo/hugo-extended" = ["0.154.4"]
"npm:wrangler" = ["3.114.16"]
# "npm:node-vibrant" = ["3.1.4"]
# "npm:photoswipe" = ["4.1.3"]
# "npm:katex" = ["0.15.6"]
#"npm:"
#go = ["1.22.0"]
