name = "jjgadgets-tech"
pages_build_output_dir = "public"
compatibility_date = "2026-02-08"
minify = true
build.command = "npm install || true; hugo --baseURL $CF_PAGES_URL --minify --gc"

[vars]
HUGO_VERSION = "0.155.2"
NODE_VERSION = "18.20.8"

# [env.production.vars]
# HUGO_VERSION = "0.155.2"
